# ❗ Enforce running CocoaPods via Bundler (vendor/bundle) and NOT global pods
# 
# Why: We rely on Bundler to install and manage the correct CocoaPods version (`vendor/bundle`)
#      instead of using the globally installed CocoaPods, which may be outdated or incompatible.
#      Running 'pod install' directly without 'bundle exec' could break builds due to version mismatches.
# 
# How: If 'vendor/bundle' is missing, we abort early with a clear error message.
# 
# See also: https://bundler.io/
unless defined?(Bundler)
  abort <<~MSG
  ❌ CocoaPods must be run through Bundler (vendor/bundle).
  ➡️  Please use: 'yarn pod:install'
  (instead of running 'pod install' manually or through npx)
MSG
end

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Dependecies required for Ramp.network:
# source 'https://github.com/CocoaPods/Specs.git'

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled(["Debug"])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'rifWallet' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'rifWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

