export enum SETTINGS {
  DEFAULT_CHAIN_TYPE = 'DEFAULT_CHAIN_TYPE', //the chain id used by default when creating a new account
  RIF_WALLET_SERVICE_URL = 'RIF_WALLET_SERVICE_URL',
  EXPLORER_ADDRESS_URL = 'EXPLORER_ADDRESS_URL',
  RPC_URL = 'RPC_URL',
  SMART_WALLET_FACTORY_ADDRESS = 'SMART_WALLET_FACTORY_ADDRESS',
  RIF_RELAY_SERVER = 'RIF_RELAY_SERVER',
  RELAY_VERIFIER_ADDRESS = 'RELAY_VERIFIER_ADDRESS',
  DEPLOY_VERIFIER_ADDRESS = 'DEPLOY_VERIFIER_ADDRESS',
  QR_READER_BITCOIN_DEFAULT_NETWORK = 'QR_READER_BITCOIN_DEFAULT_NETWORK',
  AUTH_CLIENT = 'AUTH_CLIENT',
  RIF_WALLET_KEY = 'RIF_WALLET_KEY',
  WALLETCONNECT2_PROJECT_ID = 'WALLETCONNECT2_PROJECT_ID',
  BTC_EXPLORER_ADDRESS_URL = 'BTC_EXPLORER_ADDRESS_URL',
  TERMS_AND_CONDITIONS_URL = 'TERMS_AND_CONDITIONS_URL',
}
