name: Android Build SDK

on:
  release:

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn
          yarn ganache &
          yarn test
          yarn lint

      - name: Build Android Release
        run: |
          cd android && ./gradlew app:assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
