name: iOS Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: xcode-select -p
    - name: Install dependencies
      run: yarn
    - name: Install pod dependencies
      run: pod install
      working-directory: ios
    - name: Build iOS (debug)
      run: "xcodebuild \
        -workspace ios/sWallet.xcworkspace \
        -scheme sWallet \
        clean archive \
        -sdk iphoneos \
        -configuration Debug \
        -UseModernBuildSystem=NO \
        -archivePath $PWD/sWallet \
        CODE_SIGNING_ALLOWED=NO"
